#!/bin/bash

### Подгрузка alias'ов ###
if [ -f ~/.userrc/aliases ]; then source ~/.userrc/aliases; fi

case "$CC_COMPILER" in
	"clang")
		# Выбран clang.
		export LLVM=1;
		export LLVM_IAS=1;
		export CC='/bin/clang';
		export CXX='/bin/clang++';
		export CPP='/bin/clang -E';
		export CXXCPP='/bin/clang++ -E';
		export CPP="$CXX";
		export LD='/bin/ld.lld';
		export AR='/bin/llvm-ar';
		export NM='/bin/llvm-nm';
		export STRIP='/bin/llvm-strip';
		export READELF='/bin/llvm-readelf';
		export HOSTCC='/bin/clang';
		export HOSTCXX='/bin/clang++';
		export HOSTAR='/bin/llvm-ar';
		export HOSTLD='/bin/ld.lld';
		export OBJCOPY='/bin/llvm-objcopy';
		export OBJDUMP='/bin/objdump';
		export CCDEPMODE='depmode=gcc3';
		export BUILD_FLAGS="LLVM=1 LLVM_IAS=1 CC=clang CXX=clang++ LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar HOSTLD=ld.lld OBJCOPY=llvm-objcopy OBJDUMP=objdump";
		;;
	"gcc")
		# Выбран gcc.
		export LLVM=0;
		export LLVM_IAS=0;
		export CC='gcc';
		export CXX='g++';
		export CPP='gcc -E';
		export CXXCPP='g++ -E';
		export CPP="$CXX";
		export LD='ld';
		export AR='ar';
		export NM='nm';
		export STRIP='strip';
		export READELF='readelf';
		export HOSTCC='gcc';
		export HOSTCXX='g++';
		export HOSTAR='ar';
		export HOSTLD='ld';
		export OBJCOPY='objcopy';
		export OBJDUMP='objdump';
		export CCDEPMODE='depmode=gcc3';
		;;
	*)
		echo "[Warning] Unknown compiler. Skipping ...";
		;;
esac;

