#!/bin/bash

### Подгрузка alias'ов ###
if [ -f ~/.userrc/aliases ]; then source ~/.userrc/aliases; fi

### Установка переменных в соответствие с выбранным компилятором ###
case "$CC_COMPILER" in
	"clang")
		# Выбран clang.
		export LLVM=1;
		export LLVM_IAS=1;
		export CC='/bin/clang';
		export CXX='/bin/clang++';
		export CPP='/bin/clang -E';
		export CXXCPP='/bin/clang++ -E';
		export LD='/bin/ld.lld';
		export AR='/bin/llvm-ar';
		export NM='/bin/llvm-nm';
		export STRIP='/bin/llvm-strip';
		export READELF='/bin/llvm-readelf';
		export HOSTCC="$CC";
		export HOSTCXX="$CXX";
		export HOSTAR="$AR";
		export HOSTLD="$LD";
		export OBJCOPY='/bin/llvm-objcopy';
		export OBJDUMP='/bin/objdump';
		export CCDEPMODE='depmode=gcc3';
		;;
	"gcc")
		# Выбран gcc.
		# Сброс всех переменных до значений по умолчанию.
		unset LLVM;
		unset LLVM_IAS;
		unset CC;
		unset CXX;
		unset CPP;
		unset CXXCPP;
		unset LD;
		unset AR;
		unset NM;
		unset STRIP;
		unset READELF;
		unset HOSTCC;
		unset HOSTCXX;
		unset HOSTAR;
		unset HOSTLD;
		unset OBJCOPY;
		unset OBJDUMP;
		unset CCDEPMODE;
		;;
	*)
		echo "[Warning] Unknown compiler. Skipping ...";
		;;
esac;

